version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
      - elk
    
  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

networks:
  elk:
    driver: bridge