FROM "docker.elastic.co/beats/metricbeat:{{ metricbeat_version }}"
USER root
RUN rm -f "{{ metricbeat_container_config_file }}"
ADD metricbeat.yml "{{ metricbeat_container_config_file }}"
RUN chmod -v o+r "{{ metricbeat_container_config_file }}"
USER metricbeat