metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - fsstat
    - load
    - memory
    - network
    - process
    - process_summary
    - uptime
  enabled: true
  period: 10s
  processes: ['.*']

  cpu.metrics: ["percentages"]
  core.metrics: ["percentages"]

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

setup.kibana.host:
  host: "127.0.0.1:5601"

output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
