---
- name: Create necessary directory structure in host
  file:
    path: "{{ metricbeat_path }}/metricbeat"
    state: directory

- name: Copy docker-compose.yml to host
  copy:
    src: metricbeat-docker/docker-compose.yml
    dest: "{{ metricbeat_path }}"
- name: Copy Dockerfile template to host
  template:
    src: metricbeat-docker/Dockerfile.j2
    dest: "{{ metricbeat_config_path }}/Dockerfile"
- name: Copy Metricbeat configuration to host
  copy:
    src: "{{ inventory_dir }}/metricbeat.yml"
    dest: "{{ metricbeat_config_path }}"
